### ISSUE TITLE
[Bot Issue] startup generates SERVER_LOGS_URL as a folder, then complains that it's a folder

### ISSUE THREAD

**Issue by lifehackerhansol** [nh-server/Kurisu#1046]
**Issue Description**
```
kurisu_1  | Traceback (most recent call last):
kurisu_1  |   File "/home/kurisu/kurisu.py", line 74, in <module>
kurisu_1  |     SERVER_LOGS_URL = get_env('SERVER_LOGS_URL')
kurisu_1  |   File "/home/kurisu/kurisu.py", line 64, in get_env
kurisu_1  |     with open(contents_file, 'r', encoding='utf-8') as f:
kurisu_1  | IsADirectoryError: [Errno 21] Is a directory: '/run/secrets/server_logs_url'
kurisu_1 exited with code 1
```

When first running this, it generated a `server_logs_url.txt`, but it wasn't a text file it was a folder. Am I missing something? I am just running like the README says.

**Comment by ihaveamac** [comment]
I imagine this is because Docker is treating secrets like mounts, and mounts are typically directories. When it sees it doesn't exist, it creates it as a directory.

**Comment by ihaveamac** [comment]
a60b377d2b3eea5c45a0920fdc19d110112cdc56
