### ISSUE TITLE
[Bot Issue] CTRTransfer images are still 11.15.0-47

### ISSUE THREAD

**Issue by lifehackerhansol** [nh-server/Kurisu#1123]
**Issue Description**
The commit that bumped versions for the 11.16 update changed this. It should be reverted, we have no 11.16 CTR images.

**Comment by Gruetzig** [comment]
I think that issue can be closed https://github.com/nh-server/Kurisu/pull/1122

**Comment by lifehackerhansol** [comment]
You could have at least made the PR automatically close this...
