### ISSUE TITLE
[Error Submission] Error 001-0803

### ISSUE THREAD

**Issue by Gandalf1783** [nh-server/Kurisu#1124]
**Console**

3DS

**Error Code**

001-0803

**Error Description**

It seems like this is any of the following:
1. ONLINE-Multiplayer server not found
2. SSL Problem between 3ds and the nasc server.

**Comment by lifehackerhansol** [comment]
Duplicate of #1067.

Already added in commit 3d7a782186419f1061679b1b83ccfd7ec33a855f.
