### ISSUE TITLE
[Bot Issue] 

### ISSUE THREAD

**Issue by carltonswanks** [nh-server/Kurisu#1137]
**Issue Description**
not an issue but u should unban me on discord, I have actual questions now

**Comment by carltonswanks** [comment]
I retract my previous statements in the discord

**Comment by eip618** [comment]
as you identified, this is not an issue and so is being closed

**Comment by carltonswanks** [comment]
> as you identified, this is not an issue and so is being closed

ok, can I be unbanned

**Comment by eip618** [comment]
well you pretty clearly stated your intent to try and scam someone else out of money, so... no

**Comment by carltonswanks** [comment]
> well you pretty clearly stated your intent to try and scam someone else out of money, so... no

u readin too much into it

**Comment by eip618** [comment]
> > well you pretty clearly stated your intent to try and scam someone else out of money, so... no
> 
> u readin too much into it

u directly stated that u are planning on selling a bricked console as a working console then claiming it was damage during shipping
you *literally* said this

**Comment by carltonswanks** [comment]
> > > well you pretty clearly stated your intent to try and scam someone else out of money, so... no
> > 
> > 
> > u readin too much into it
> 
> u directly stated that u are planning on selling a bricked console as a working console then claiming it was damage during shipping you _literally_ said this

u right das my fault, can u watch fight club on a 3ds?

**Comment by carltonswanks** [comment]
> > > > well you pretty clearly stated your intent to try and scam someone else out of money, so... no
> > > 
> > > 
> > > u readin too much into it
> > 
> > 
> > u directly stated that u are planning on selling a bricked console as a working console then claiming it was damage during shipping you _literally_ said this
> 
> u right das my fault, can u watch fight club on a 3ds?

im also a compulsive liar (sometimes its funny)

**Comment by eip618** [comment]
i think we've seen enough here
