### ISSUE TITLE
[Error Submission] Error 160-2793

### ISSUE THREAD

**Issue by KirbyKing186** [nh-server/Kurisu#1161]
**Console**

WiiU

**Error Code**

160-2793

**Error Description**

Error simply states an error has occurred and to hold the power button down to turn off. This was caused when opening the "Nintendont Forwarder". The only settings I had enabled/changed were Video Settings (690), WiiU Widescreen (On), Force Widescreen (On), and Force Progressive Mode (On). I have opened it multiple times before and after the error, and I experienced no problems other than this one time. I have no external hard drive nor any WiiU accessories, just a 64GB microSD card in an adapter. See the image for further details.

![image](https://user-images.githubusercontent.com/125282065/218480720-7df490be-c370-44e3-9f1a-f9385105904a.png)

**Comment by Robelary** [comment]
I got the same error after running vwii or any wii injected game. My hdd doesnt work on the back usb ports and i'm on 5.5.6 and tirumisu last version just like u.

**Comment by Lazr1026** [comment]
This is due to missing files on the vWii. Update the console after using vWii Decaffeinator, this will redownload the missing files to fix it.

**Comment by Cueropedo** [comment]
Happens to me with WiiVC, but vWii hasn't been messed with. After getting this error it boots normally the next time.
Here is some information from system log:
`00;01;26;910: CMPT: Imgs: 12ac2e80 (12582912 bytes)
00;01;31;233: TVESetWiiCompatEx: WiiCompat setting timed out. Revert setting, hdmi_err_stat:8
00;01;31;233: CMPT: failed: compat.c:68: Failed to configure AV mode: -9
00;01;31;233: CMPT: SCREEN_ERROR
00;01;31;275: [launch.cpp:237] Err:failed to launch compat mode: -9
00;01;31;275: [launch.cpp:238] nn::hai encountered a FATAL error: 160-2793(-9)`
