### ISSUE TITLE
[Error Submission] Error 009-2001

### ISSUE THREAD

**Issue by Cybelyrium** [nh-server/Kurisu#1166]
**Console**
3DS

**Error Code**
009-2001

**Error Description**
Error happens when trying to use Pokémon Bank after having performed a region change because of NNID issues.
To fix, redo the region change process and return to the console's original region.

**Comment by MechanicalDragon0687** [comment]
more specifically, this along with 007-2001 means: This 3ds is registered to another region's eshop.
to resolve it: region change the console to the original region and delete the eshop profile from the eshop settings

There are additional errors that may occur for jpn models such as 005-5602 (owns titles from another region) which require system transfer to resolve
