### ISSUE TITLE
[Error Submission] Error 015-5015

### ISSUE THREAD

**Issue by nchatterjee143** [nh-server/Kurisu#1240]
**Console**

3DS (New XL, just in case)

**Error Code**

015-5015

**Error Description**

Just says "An error occured. Please try again later." Tried accessing Miiverse with the Pretendo switch on Nimbus, and I even asked the Pretendo people and they couldn't figure it out either.

**Comment by ratcinee** [comment]
Same problem here, did you ever figure it out ?

**Comment by nchatterjee143** [comment]
@ratcinee Yep. It's Pretendo's problem really. It's just that for some reason I wasn't signed into my PNID when trying to access Miiverse (Juxtaposition).
