### ISSUE TITLE
[Error Submission] Error 006-0303

### ISSUE THREAD

**Issue by Dorsalspider933** [nh-server/Kurisu#1256]
**Console**

3DS

**Error Code**

006-0303

**Error Description**

Unable to connect to the server. Please try again later.

**Comment by lifehackerhansol** [comment]
Related: https://pretendo.network/blog/12-23-23

Wii U error code: 106-0303

**Comment by Andremccalpin** [comment]
> **Console**
> 
> 3DS
> 
> **Error Code**
> 
> [006-0303](tel:006-0303)
> 
> **Error Description**
> 
> Unable to connect
