### ISSUE TITLE
[Error Submission] Error 032-1222

### ISSUE THREAD

**Issue by TophattedWasTaken** [nh-server/Kurisu#1365]
**3DS**

**032-1222**

Browser doesn't work on Japan consoles. This happens sometime between the 14th and the 19th of every month due to maintenance.
Solution is to wait for the browser to leave maintenance. If modding the console, you should do safecerthax or MSET9 depending on your console's model and version.

**Comment by lilyuwuu** [comment]
it's specifically on the 14th (15th cest 1am-6am) with a short recurrence on the 19th due to filter of the jp only browser filter
