### ISSUE TITLE
Kurisu reply if DM block

### ISSUE THREAD

**Issue by Sonlen1414** [nh-server/Kurisu#229]
Possibly have Kurisu reply in the channel a message was deleted if DMs are diabled to inform the person why the message was deleted

**Comment by GriffinG1** [comment]
It'd need to send a different message than it currently does, since the current _includes_ the message that was deleted. Hmm..

**Comment by GriffinG1** [comment]
Not in channel, but it'll at least let staff know for reference in action

**Comment by Jan200101** [comment]
Suggestion:
If the users DMs are not accessable tell the user he said a blacklisted word

**Comment by FrozenChen** [comment]
Fixed in abfe86d0d65295702454f6fb38cff3ecc870481b
