### ISSUE TITLE
.vguides command too big

### ISSUE THREAD

**Issue by xCaseyKill10** [nh-server/Kurisu#250]
Hi,

I believe the .vguides command is too big and has a lot of unnecessary sentences, spacing, and lines. It should be revised with a smaller embed like this 
<img width="286" alt="chrome_2017-10-20_19-40-05" src="https://user-images.githubusercontent.com/32882595/31845433-a13965de-b5ce-11e7-8562-0cc7f56db642.png">

**Comment by Mike15678** [comment]
I think this can be closed now since https://github.com/nh-server/Kurisu/commit/4b945a315b2ca2474aceda795de9c5bdbe97ca30 fixed this.
