### ISSUE TITLE
Switchthem.es is in the list of domains that misdirect

### ISSUE THREAD

**Issue by Cr3atable** [nh-server/Kurisu#345]
A while ago the person who owned 3dsthem.es bought switchthem.es and made it go to gay furry porn. A little while later, the domain was bought by pwsincd (someone who is respectable in the community) and loaned to Team Qcean, who provide themes for the community. Now you'll get a warning for visiting a purely legal, and non-malicious website. The issue lies here: https://github.com/nh-server/Kurisu/blob/master/addons/events.py

**Comment by EdTheNerd** [comment]
We would need to know more about the site's plans, as right now it has nothing on it.

It is correct that we wouldn't consider it miss-info now, but currently, the only way to transfer a "ready to use" switch theme is with it containing a copyrighted portion of the Switch OS. There is no simple themeing app like on 3DS.
This would put it in the _worse_ category of piracy sites, if that's how themes are to be hosted.

If the site only plans to host jpg/png's, leaving it up to the user to make them into a theme, AND the site does not plan to have links to copyrighted code needed to make said themes, then that would of course be fine.

**Comment by Oreo639** [comment]
This can be closed now. https://github.com/nh-server/Kurisu/pull/416
