### ISSUE TITLE
Missing Licensee and Licening year

### ISSUE THREAD

**Issue by Jan200101** [nh-server/Kurisu#454]
The [License](https://github.com/nh-server/Kurisu/blob/master/LICENSE.txt#L189) is clearly missing a licensee and a licensing year
I am not too familar with the Apache 2 license but I see this as a simple issue worth fixing

**Comment by MechanicalDragon0687** [comment]
this looks like the appendix is attempting to tell the user how to make it clear their code is covered under that specific license rather than applying a date/owner. it is an instructional portion of the license describing usage.

**Comment by Jan200101** [comment]
I'd argue otherwise and that without a direct licensee copyright is a bit iffy especially with forks
