### ISSUE TITLE
guiformat mirror?

### ISSUE THREAD

**Issue by techmuse8** [nh-server/Kurisu#841]
![Screen Shot 2020-10-19 at 8 06 12 PM](https://user-images.githubusercontent.com/44119098/96524537-8f880980-1246-11eb-8d8f-adf8979f7106.png)
According to this https://downforeveryoneorjustme.com/ridgecrop.demon.co.uk?proto=http&www=1 the site where it links guiformat in Kurisu is down

**Comment by GlaZedBelmont** [comment]
issue was fixed in https://github.com/nh-server/Kurisu/pull/846
