### ISSUE TITLE
"Your support description appears to be unknown" on 3DS is replicatable in one way

### ISSUE THREAD

**Issue by CyberYoshi64** [nh-server/Kurisu#866]
I had issues with my o2DS with error codes which Kurisu describes those with said message and the app that caused these was the eShop/MINT applet.

I have told about how I fixed it on the HB-Discord yesterday.

Basically, whether you'd use the DevUnit "Config" program or write a homebrew capable of changing the system settings,
if the language setting happens to become invalid (like 0xF, "undefined") Nintendo servers refuse to connect to this 3DS with this bugged out setting. Not even some MK7 WWs are possible. Friend list still works though.

There may be other reasons that would originate from corrupted settings.

The way to fix it (in this case) is to change the language back in System Settings.
(If English is the language to switch to, select another one before tapping English since the 3DS does only default text strings to English.)
↑ Because of this requiring the languages option, JPN, CHN, TWN and KOR consoles have to rely on a homebrew program to switch it back since the System Settings on those consoles don't have a visible language setting.

I have to be honest here: This is not common whatsoever. However, there may (and even are) homebrew apps that screw with consoles rather than do what they were advertised to.

Ofc I have full guilt for this problem on my o2DS since I downloaded a random (kinda sus) homebrew without asking if it's actually OK to use but it was interesting to discover and examine this error nontheless.

**Comment by FrozenChen** [comment]
Thanks for your submission, can you also tell us which error code are you referring to?

**Comment by CyberYoshi64** [comment]
The following error codes were derived from this invalid language setting I could find:
022-5363 (when loading the NNID settings)
007-2924 (When trying to download system/game updates or open the theme shop)
009-2924 (When opening the Nintendo eShop)
014-0013 (When opening System Transfer)

When trying to play MK7 online, no error code is output but it still refuses to connect.

**Comment by CyberYoshi64** [comment]
Also, another give-away that the language setting was corrupted is that the homebrew launcher and my own homebrew titles can sometimes show corrupted, debug or empty strings instead.

![2020-12-21_21-01-37 506_bot](https://user-images.githubusercontent.com/35138367/102817690-8a734200-43d0-11eb-97e2-6eea2941265e.png)
Also, the friend list favourite title menu also shows corrupted names (probably because of the menu reading out of bounds)

I couldn't find any more error codes for it, too.
