### ISSUE TITLE
Implement some kind of testing on GitHub Actions

### ISSUE THREAD

**Issue by ihaveamac** [nh-server/Kurisu#870]
Seeing that travis-ci won't be entirely free for oss projects (starting 2021), this would be a good time to set up testing with GitHub.

**Comment by FrozenChen** [comment]
Implemented eb4583d653a28233eb21380e569e6d6d6ee8bf5e although more could be done with flake8, this should suffice for the time as a 1:1 replacement to what travis-ci did

**Comment by FrozenChen** [comment]
Fully implemented in db59e01da4a61efc8d63d434f9545d9b939840cc
