### ISSUE TITLE
[Error Submission] Error 150-3032

### ISSUE THREAD

**Issue by Akorax** [nh-server/Kurisu#879]
**Console:** WiiU
**Error Code:** 150-3032
**Error Description:** PERMISSION_ERROR

When the system tried to access files mapped to NAND that was copied from RedNAND to SysNAND a permission error occurred.
See the log at: https://pastebin.com/S81kApYg (up for 1 year from today)
I do not know if more errors are mapped to this number.

**Comment by FrozenChen** [comment]
Implemented in 3185ed8. Thanks for your submission.
