### ISSUE TITLE
[Error Submission] Error 155-0209

### ISSUE THREAD

**Issue by TxMat** [nh-server/Kurisu#898]
**Console**

Wiiu

**Error Code**

155-0209

**Error Description**

The meta.xml file could not be loaded because its format was invalid.

raised when the XML does not pass the verification

does not normally occurs with a a normal WiiU Use but it's intresting

also 155-0210 is when there is no meta.xml at all

**Comment by FrozenChen** [comment]
Given the information for this error was taken 1:1 from the SDK, it wont be added
