### ISSUE TITLE
[Bot Issue] .nickme cooldown counter is not reset when user does not have permissions

### ISSUE THREAD

**Issue by rsxRi** [nh-server/Kurisu#909]
When attempting to change nickname using `.nickme` and the user does not have either crc or nitro booster, or there is a permissions error the cooldown counter is not reset.
I'm unsure if this is intended or not, however I'd like to think that it isn't, since there would be no need to limit how often somebody can fail to change their nickname.
from looking at the command, this should be resolved by adding `ctx.command.reset_cooldown(ctx)` to a newline under lines 255 and 248 in `extras.py`, but I could be wrong.

**Comment by FrozenChen** [comment]
Doesnt seem much of a issue to me, even if the cooldown is reset
